env:
  browser: true
  es2021: true
extends:
  - next/core-web-vitals
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:@typescript-eslint/strict
  - plugin:github/recommended
  - plugin:unicorn/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
  - react
  - github
  - json-format
  - unicorn
  - promise
  - prettier
rules:
  unicorn/prevent-abbreviations:
    - error
    - ignore:
        - "next-env"
  unicorn/prefer-module:
    - off
  import/no-commonjs:
    - off
  promise/always-return: error
  promise/no-return-wrap: error
  promise/param-names: error
  promise/catch-or-return: error
  promise/no-native: off
  promise/no-nesting: warn
  promise/no-promise-in-callback: warn
  promise/no-callback-in-promise: warn
  promise/avoid-new: warn
  promise/no-new-statics: error
  promise/no-return-in-finally: warn
  promise/valid-params: warn
