extends:
  - plugin:vitest/all
rules:
  vitest/prefer-expect-assertions: off
  vitest/no-hooks:
    - error
    - allow:
        - afterEach
        - afterAll
        - beforeAll
        - beforeEach
  import/named: off
